services:
  cura-postgres:
    image: postgres:16
    container_name: cura-postgres
    environment:
      POSTGRES_DB: cura
      POSTGRES_USER: eman
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - cura_pgdata:/var/lib/postgresql/data

volumes:
  cura_pgdata:
